name: deploy-prod2

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4

      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PROD2_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_PROD2_KNOWN_HOSTS }}
          # To disable host key checking (insecure!):
          #ssh-disable-host-key-checking: true

      - name: Deploy to production
        env:
          SSH_HOST: ${{ secrets.SSH_PROD2_HOST }}
          SSH_USER: ${{ secrets.SSH_PROD2_USER }}
          DEPLOY_PATH: ${{ secrets.PROD2_DEPLOY_PATH }}
        run: dep deploy production2
